### ISSUE TITLE
nickel/src/video/input.cpp 中的第81行`auto parseResult = toml::parse_file("./nickel-config.toml");`因项目中没这个文件而报错

### ISSUE THREAD

**Issue by shiyi9** [VisualGMQ/NickelEngine#12]
已经仔细搜索过，项目中并没有 nickel-config.toml 这个配置文件，因此编译到 nickel/src/video/input.cpp 第86行时会报错，相关的那几行代码是这样的：
`
// In ”nickel/src/video/input.cpp“ 81-86 lines
auto parseResult = toml::parse_file("./nickel-config.toml");
    if (!parseResult) {
        LOGW(log_tag::Config, "parse ",
             "nickel-config.toml"
             " failed, use default actions.\nError: ",
             parseResult.error());
`

**Comment by VisualGMQ** [comment]
这个文件是可选的。如果没有运行时会报一个Log。
编译不会出错
